version: '3'

services:
  app:
    image: lobre/wix-proxy
    container_name: wix-proxy
    ports:
      - 80:80
    environment:
      - HOST=example.com
      - PROTO=http
      - WIX_USER=myuser
      - WIX_SITE=mysite
